<?php
$z[0]=Array("field","",12,38);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",84,112);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",115,144);
$z[2][4]['name']="typename";
$z[3]=Array("channel","       \r\n              <div class=\"li\"><a href=\"[field:typelink/]\">·[field:typename/]</a></div>\r\n    ",193,429);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[3][4]['currentstyle']="<div class=";
$z[3][4]['li lis"><a href']="~typelink~";
$z[3][4]['>~typename~</a> </div>"']="";

?>