<?php
$z[0]=Array("field","",31,59);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",68,94);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",96,125);
$z[2][4]['name']="typename";
$z[3]=Array("channel","       \r\n            <li ><a href=\"[field:typelink/]\">·[field:typename/]</a></li>\r\n    ",151,368);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='curr'>~typename~</a> </li>";

?>