<li ><a href="/jiajuzhaomingguangyuan.html" class="curr">家居照明光源</a>
          <ul  style=" display:block">
            <li ><a href="/tongdengxilie.html" class="curr">LED筒灯系列</a></li>
            <li ><a href="/xidingdengxilie.html" >LED吸顶灯系列</a></li>
            <li ><a href="/shedengxilie.html" >LED射灯系列</a></li>
            <li ><a href="/huyantaidengxilie.html" >LED护眼台灯系列</a></li>
            <li ><a href="/chaobaotongdengxilie.html" >LED超薄筒灯系列</a></li>
            <li ><a href="/lazhudengxilie.html" >LED蜡烛灯系列</a></li>
          </ul>
        </li>
      
      
      
      
      
      
      
      </ul>
      <p>&nbsp;</p>
    </div>
    <div class="barTwo"><img src="/images/cont.jpg"/><br/>
      <p><strong>东莞市迪奥照明科技有限公司</strong><br />
        电话：{dede:global.cfg_dianhua