<?php
$z[0]=Array("field","",22,50);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",59,85);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",87,116);
$z[2][4]['name']="typename";
$z[3]=Array("channel","       \r\n            <li ><a href=\"[field:typelink/]\">·[field:typename/]</a></li>\r\n    ",142,359);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='curr'>~typename~</a> </li>";

?>