
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:title itemname="留言主题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:title>

<field:tel itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="电子邮件" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:contenta itemname="您的留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:contenta>
