<?php
$z[0]=Array("field","",14,42);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",51,77);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",79,108);
$z[2][4]['name']="typename";
$z[3]=Array("field","",137,183);
$z[3][4]['name']="typeid";
$z[3][4]['function']="GetTopid(@me)";
$z[4]=Array("channel","       \r\n            <li ><a href=\"[field:typelink/]\">·[field:typename/]</a></li>\r\n    ",191,408);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='curr'>~typename~</a> </li>";

?>