<?php
$z[0]=Array("channelartlist","\r\n    <div class=\"menu\">\r\n      <h2><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></h2>\r\n      <ul>\r\n        {dede:channel type='son' noself='yes'}\r\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        {/dede:channel}\r\n      </ul>\r\n    </div>\r\n    ",45,450);
$z[0][4]['typeid']="1,4,7,13,17,24,27";
$z[1]=Array("global","",595,623);
$z[1][4]['name']="cfg_mingcheng";
$z[2]=Array("include","",647,680);
$z[2][4]['filename']="qq.htm";

?>