<?php
$z[0]=Array("field","",254,276);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",328,357);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",390,448);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1748,1783);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1826,1861);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",1924,1953);
$z[6][4]['name']="position";
$z[7]=Array("field","",1982,2011);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n      <li>\r\n        <div class=\"pimg\"><a href=\"[field:arcurl /]\" title=\"[field:title /]\"><img src=\"[field:litpic /]\"/></a></div>\r\n        <div class=\"ptit\"><span>[field:title /]</span>\r\n          <p>[field:description /]...<a href=\"[field:arcurl /]\">查看详情</a></p>\r\n        </div>\r\n      </li>\r\n",2055,2392);
$z[8][4]['pagesize']="6";
$z[9]=Array("pagelist","",2480,2551);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2596,2633);
$z[10][4]['filename']="footer.htm";

?>