<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",321,348);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",445,475);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",4307,4343);
$z[3][4]['filename']="head1.htm";
$z[4]=Array("arclist","\r\n        <li class=\"indexFlashBanner0[field:global name=autoindex/] selected\">\r\n          <article class=\"indexFlashContent\"><a href=\"#\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"banner4\"></a></article>\r\n        </li>\r\n",4593,4860);
$z[4][4]['typeid']="45";
$z[5]=Array("global","",13549,13577);
$z[5][4]['name']="cfg_mingcheng";
$z[6]=Array("sql","\r\n      [field:content function='cn_substr(html2text(@me),300)'/]\r\n",13630,13767);
$z[6][4]['sql']="Select content from #@__arctype where id=2";
$z[7]=Array("arclist","\r\n            <li><span>[[field:pubdate function=\"GetDateMK(@me)\"/]]</span><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n",14033,14234);
$z[7][4]['typeid']="17,24";
$z[7][4]['row']="5";
$z[8]=Array("include","",14308,14345);
$z[8][4]['filename']="footer.htm";

?>