<?php
$z[0]=Array("field","",62,121);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("field","",127,155);
$z[1][4]['name']="siteurl";
$z[2]=Array("channelartlist","\r\n        <li  class=\"{dede:field.currentstyle/}\" >\r\n          <div class=\"title1\"> <a href=\"{dede:field name='typeurl'/}\"> {dede:field name='typename'/}</a></div>\r\n          <div class=\"slist\"> {dede:channel type='son' noself='yes' currentstyle=\"\r\n            <div class=\"li lis\"><a href='~typelink~' >~typename~</a> </div>\r\n            \" }\r\n            <div class=\"li\"><a href=\"[field:typelink/]\">·[field:typename/]</a></div>\r\n            {/dede:channel} </div>\r\n        </li>\r\n        ",245,821);
$z[2][4]['typeid']="8,9,10,11,12";
$z[2][4]['currentstyle']="select";
$z[3]=Array("global","",993,1021);
$z[3][4]['name']="cfg_mingcheng";
$z[4]=Array("global","",1055,1081);
$z[4][4]['name']="cfg_dianhua";
$z[5]=Array("global","",1139,1160);
$z[5][4]['name']="cfg_dh";
$z[6]=Array("global","",1185,1213);
$z[6][4]['name']="cfg_chuanzhen";
$z[7]=Array("global","",1238,1262);
$z[7][4]['name']="cfg_email";
$z[8]=Array("global","",1287,1311);
$z[8][4]['name']="cfg_dizhi";

?>