<?php
$z[0]=Array("field","",65,124);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("field","",130,158);
$z[1][4]['name']="siteurl";
$z[2]=Array("channel","\r\n <li><a href=\"[field:typelink/]\" title=\"[field:typename function='substr(@me,0,15)'/]\" >[field:typename function='substr(@me,0,15)'/]</a></li>\r\n",185,447);
$z[2][4]['type']="sun";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='curr'>~typename~</a> </li>";
$z[3]=Array("global","",581,609);
$z[3][4]['name']="cfg_mingcheng";
$z[4]=Array("global","",643,669);
$z[4][4]['name']="cfg_dianhua";
$z[5]=Array("global","",727,748);
$z[5][4]['name']="cfg_dh";
$z[6]=Array("global","",773,801);
$z[6][4]['name']="cfg_chuanzhen";
$z[7]=Array("global","",826,850);
$z[7][4]['name']="cfg_email";
$z[8]=Array("global","",875,899);
$z[8][4]['name']="cfg_dizhi";

?>