<?php
$z[0]=Array("field","",254,276);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",328,357);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",390,448);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1748,1783);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1826,1861);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",1931,1960);
$z[6][4]['name']="position";
$z[7]=Array("field","",1991,2020);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n      <li><span>[[field:pubdate function=\"GetDateMK(@me)\"/]]</span><a href=\"[field:arcurl /]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n",2053,2234);
$z[8][4]['pagesize']="12";
$z[9]=Array("pagelist","",2299,2370);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2407,2444);
$z[10][4]['filename']="footer.htm";

?>