<?php
$z[0]=Array("field","",254,276);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",328,357);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",390,448);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1748,1783);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1826,1862);
$z[5][4]['filename']="left2.htm";
$z[6]=Array("field","",1930,1959);
$z[6][4]['name']="position";
$z[7]=Array("field","",1990,2019);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n        <li><a href=\"[field:arcurl /]\" title=\"[field:title /]\"><img src=\"[field:litpic /]\"/><span>[field:title /]</span></a></li>\r\n",2067,2235);
$z[8][4]['pagesize']="12";
$z[9]=Array("pagelist","",2313,2384);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2421,2458);
$z[10][4]['filename']="footer.htm";

?>